#!/usr/bin/env python3
"""
Migrate existing OpenSpec project to Plugin Mode (v3.2)

Scans .claude/settings.json and removes hook commands that reference
local .claude/hooks/*.py files which are now provided by the plugin.
Also removes legacy .claude/commands/*.md files that duplicate a
plugin-provided skill of the same name (causes double slash-command
entries in the palette, see issue #24).

The plugin's hooks/hooks.json already declares all core hooks globally
for every project with the plugin enabled. Project-level settings.json
must NOT use ${CLAUDE_PLUGIN_ROOT} — that variable is only valid inside
a plugin's own hooks/hooks.json.

Handles both legacy command formats:
  v2 wrapper: if [ -f "${CLAUDE_PROJECT_DIR}/.claude/hooks/foo.py" ]; then python3 ... ; fi
  v3 direct:  python3 /absolute/path/.claude/hooks/foo.py

Usage:
    python3 migrate_to_plugin.py /path/to/project          # Dry run
    python3 migrate_to_plugin.py /path/to/project --apply  # Apply changes
"""

import json
import re
import sys
from pathlib import Path

PLUGIN_ROOT = Path(__file__).parent

# Core hooks — live in ${CLAUDE_PLUGIN_ROOT}/core/hooks/
# These are deleted from a project's .claude/hooks/ on --apply (the plugin
# provides them globally). NOTE: hook_utils.py and config_loader.py are NOT
# here — they are shimmed instead (see SHIM_HOOKS), because project-own hooks
# import them and blind deletion would break every such hook.
CORE_HOOKS = {
    "edit_gate.py",
    "bash_gate.py",
    "post_bash.py",
    "phase_listener.py",
    "session_singleton_guard.py",
    "qa_gate.py",
    "override_token.py",
    "workflow.py",
    "migrate_state.py",
    "adversary_dialog.py",
    "claude_md_protection.py",
    "edit_verify.py",
    "post_implementation_gate.py",
    "secrets_guard.py",
    "tdd_enforcement.py",
    "worktree_write_guard.py",
}

# Module hooks — live in ${CLAUDE_PLUGIN_ROOT}/modules/<module>/hooks/
MODULE_HOOKS: dict[str, str] = {
    "ui_test_preflight.py": "ios-swiftui",
    "on_ui_test_failure.py": "ios-swiftui",
    "ui_test_debugger_hint.py": "ios-swiftui",
    "test_lock_guard.py": "ios-swiftui",
    "check_ha_restart.py": "home-assistant",
    "lovelace_screenshot_gate.py": "home-assistant",
}

# Shim hooks — utility modules that project-own hooks import directly
# (e.g. `from hook_utils import ...`). Instead of deleting these on --apply,
# we replace them with a thin shim that loads the real module from the
# installed plugin and re-exports its public attributes.
SHIM_HOOKS = {"hook_utils.py", "config_loader.py"}

# Marker on the first line of a generated shim (used for idempotency).
SHIM_MARKER = "# openspec-shim: resolves to installed plugin version"

# Shim body. __MODULE__ is replaced with the module name (e.g. hook_utils).
SHIM_TEMPLATE = '''# openspec-shim: resolves to installed plugin version
"""Shim for __MODULE__.py — generated by migrate_to_plugin.py (issue #33).

Project-own hooks import this module (e.g. ``import __MODULE__`` or
``from __MODULE__ import X``). Instead of keeping a stale local copy, this
shim loads the real module from the installed agent-os-openspec plugin and
re-exports all of its public attributes, so both import styles keep working.
"""
import importlib.util
import json
import os


def _resolve_plugin_module():
    registry = os.path.expanduser("~/.claude/plugins/installed_plugins.json")
    install_path = ""
    try:
        with open(registry) as _fh:
            _data = json.load(_fh)
        for _key, _entries in _data.get("plugins", {}).items():
            if not _key.startswith("agent-os-openspec@"):
                continue
            _entry = next(
                (_e for _e in _entries if _e.get("scope") == "user"),
                _entries[0],
            )
            install_path = _entry.get("installPath", "")
            break
    except Exception:
        install_path = ""

    if install_path:
        _module_path = os.path.join(
            install_path, "core", "hooks", "__MODULE__.py"
        )
        if os.path.isfile(_module_path):
            _spec = importlib.util.spec_from_file_location(
                "__MODULE__", _module_path
            )
            _module = importlib.util.module_from_spec(_spec)
            _spec.loader.exec_module(_module)
            return _module

    raise ImportError(
        "agent-os-openspec plugin not installed "
        "— install it or restore local hooks"
    )


globals().update(
    {
        _name: _value
        for _name, _value in vars(_resolve_plugin_module()).items()
        if not _name.startswith("__")
    }
)
'''


def _render_shim(module_name: str) -> str:
    """Render the shim body for a given module name (e.g. 'hook_utils')."""
    return SHIM_TEMPLATE.replace("__MODULE__", module_name)


def _is_shim(path: Path) -> bool:
    """True if the file's first line is the shim marker."""
    try:
        with path.open() as fh:
            first_line = fh.readline().rstrip("\n")
    except Exception:
        return False
    return first_line == SHIM_MARKER


def _find_shim_candidates(project_path: Path) -> tuple[list[Path], list[Path]]:
    """
    Return (to_replace, already_shimmed) for SHIM_HOOKS present in the project.

    - to_replace: real local copies that should become a shim.
    - already_shimmed: files already carrying the marker (idempotency).
    """
    hooks_dir = project_path / ".claude" / "hooks"
    if not hooks_dir.exists():
        return [], []
    to_replace: list[Path] = []
    already_shimmed: list[Path] = []
    for name in sorted(SHIM_HOOKS):
        f = hooks_dir / name
        if not f.exists():
            continue
        if _is_shim(f):
            already_shimmed.append(f)
        else:
            to_replace.append(f)
    return to_replace, already_shimmed

# .py filename regex — matches "foo_bar.py" or "foo-bar.py"
_PY_RE = re.compile(r'([\w][\w\-]*\.py)')


def _parse_hook_command(command: str) -> tuple[str | None, list[str]]:
    """
    Extract (py_filename, extra_args) from any hook command format.

    Works with both:
      python3 /abs/path/file.py arg1
      if [ -f "...file.py" ]; then python3 "...file.py" arg1; fi
    """
    py_files = _PY_RE.findall(command)
    if not py_files:
        return None, []

    filename = py_files[-1]

    # Text after the last .py occurrence → extra args
    last_pos = command.rfind(filename) + len(filename)
    tail = command[last_pos:]
    # Strip shell syntax: quotes, semicolons, "fi"
    tail = re.sub(r'["\';]|\bfi\b', ' ', tail).strip()
    args = tail.split() if tail else []

    return filename, args


_REMOVE = "__REMOVE__"


def _migrate_command(command: str) -> str | None:
    """
    Return _REMOVE if the command references a plugin-provided hook (should be deleted),
    or None if the command is unrelated to the plugin.

    ${CLAUDE_PLUGIN_ROOT} must NOT appear in project-level settings.json — the plugin's
    own hooks/hooks.json already registers all core hooks globally.
    """
    filename, _args = _parse_hook_command(command)
    if not filename:
        return None
    if filename in CORE_HOOKS or filename in MODULE_HOOKS:
        return _REMOVE
    return None


def _patch_settings(settings: dict, dry_run: bool) -> list[tuple[str, str, str]]:
    """
    Remove plugin hook commands from settings dict in-place.
    Returns list of (event_name, old_command, "<removed>").
    """
    changes = []
    for event_name, event_entries in settings.get("hooks", {}).items():
        for entry in event_entries:
            hooks_list = entry.get("hooks", [])
            to_remove = []
            for hook in hooks_list:
                old_cmd = hook.get("command", "")
                if _migrate_command(old_cmd) == _REMOVE:
                    changes.append((event_name, old_cmd, "<removed>"))
                    to_remove.append(hook)
            if to_remove and not dry_run:
                for h in to_remove:
                    hooks_list.remove(h)
    return changes


def _find_removable_hook_files(project_path: Path) -> list[Path]:
    """Return .claude/hooks/*.py files that are provided by the plugin."""
    hooks_dir = project_path / ".claude" / "hooks"
    if not hooks_dir.exists():
        return []
    removable = CORE_HOOKS | set(MODULE_HOOKS.keys())
    return [f for f in hooks_dir.glob("*.py") if f.name in removable]


def _find_removable_command_files(project_path: Path) -> list[Path]:
    """
    Return .claude/commands/*.md files that duplicate a plugin-provided skill.

    Legacy (pre-plugin) installs copied core/commands/*.md straight into the
    project. Once the plugin is active, these show up a SECOND time next to
    the plugin's own skill of the same name (duplicate slash command in the
    palette). Only remove files that have a matching skills/<name>/SKILL.md
    in the plugin — never touch project-specific custom commands.

    Framework-generated short aliases (see setup.generate_command_aliases) carry
    an `openspec-alias:` marker and must NOT be removed even though their name
    matches a skill. Files whose content cannot be read are conservatively
    kept (fail-safe: when in doubt, do not delete).
    """
    commands_dir = project_path / ".claude" / "commands"
    if not commands_dir.exists():
        return []
    skills_dir = PLUGIN_ROOT / "skills"
    if not skills_dir.exists():
        return []
    provided = {p.name for p in skills_dir.iterdir() if p.is_dir()}
    removable = []
    for f in commands_dir.glob("*.md"):
        if f.stem not in provided:
            continue
        try:
            content = f.read_text()
        except Exception:
            # Unreadable (binary/broken encoding): do not treat as removable.
            continue
        if "openspec-alias:" in content:
            continue
        removable.append(f)
    return removable


def _read_installed_modules(project_path: Path) -> list[str]:
    version_file = project_path / ".claude" / "framework_version.json"
    if version_file.exists():
        try:
            data = json.loads(version_file.read_text())
            return data.get("installed_modules", [])
        except Exception:
            pass
    return []


def migrate(project_path: Path, dry_run: bool = True) -> None:
    print(f"OpenSpec Plugin Migration")
    print(f"=========================")
    print(f"Project : {project_path}")
    print(f"Mode    : {'Dry Run (pass --apply to apply)' if dry_run else 'APPLY'}")
    print()

    if not (project_path / ".claude").exists():
        print("ERROR: .claude/ directory not found. Is this an OpenSpec project?")
        sys.exit(1)

    settings_path = project_path / ".claude" / "settings.json"
    if not settings_path.exists():
        print("ERROR: .claude/settings.json not found.")
        sys.exit(1)

    settings = json.loads(settings_path.read_text())
    wrote_settings = False

    # --- 1. Patch hook commands ---
    print("Scanning hook commands in .claude/settings.json ...")
    changes = _patch_settings(settings, dry_run)
    if changes:
        print(f"Found {len(changes)} plugin hook(s) to remove from settings.json:")
        for event_name, old_cmd, _action in changes:
            short_old = old_cmd if len(old_cmd) <= 80 else old_cmd[:77] + "..."
            print(f"  [{event_name}] {short_old}")
            print(f"           → <removed> (already provided by plugin hooks/hooks.json)")
        wrote_settings = True
    else:
        print("  No plugin hook commands found in settings.json.")

    # --- 2. Add OPENSPEC_ENABLED_MODULES ---
    modules = _read_installed_modules(project_path)
    env_section = settings.get("env", {})
    if modules and "OPENSPEC_ENABLED_MODULES" not in env_section:
        value = ",".join(modules)
        print(f"\nWill add env.OPENSPEC_ENABLED_MODULES = '{value}'")
        if not dry_run:
            settings.setdefault("env", {})[" OPENSPEC_ENABLED_MODULES"] = value
            settings["env"] = {k.strip(): v for k, v in settings["env"].items()}
        wrote_settings = True
    elif "OPENSPEC_ENABLED_MODULES" in env_section:
        print(f"\nenv.OPENSPEC_ENABLED_MODULES already set: {env_section['OPENSPEC_ENABLED_MODULES']}")

    # --- 3. Write settings.json ---
    if not dry_run and wrote_settings:
        settings_path.write_text(json.dumps(settings, indent=2))
        print(f"\nWritten: .claude/settings.json")

    # --- 4. Mark framework_version.json as plugin_mode ---
    version_file = project_path / ".claude" / "framework_version.json"
    if version_file.exists():
        try:
            version_data = json.loads(version_file.read_text())
            if not version_data.get("plugin_mode"):
                print("\nWill mark framework_version.json as plugin_mode=true")
                if not dry_run:
                    version_data["plugin_mode"] = True
                    version_file.write_text(json.dumps(version_data, indent=2))
                    print("  Written: .claude/framework_version.json")
        except Exception:
            pass

    # --- 5. Remove plugin hook files ---
    removable = _find_removable_hook_files(project_path)
    if removable:
        print(f"\n{len(removable)} plugin hook file(s) in .claude/hooks/ can be removed:")
        for f in removable:
            print(f"  {f.relative_to(project_path)}")
        if not dry_run:
            for f in removable:
                f.unlink()
                print(f"  Removed: {f.relative_to(project_path)}")
        else:
            print("  (will be removed with --apply)")
    else:
        print("\nNo plugin hook files found in .claude/hooks/ to remove.")

    # --- 6. Remove legacy command files that duplicate plugin skills ---
    removable_commands = _find_removable_command_files(project_path)
    if removable_commands:
        print(f"\n{len(removable_commands)} legacy command file(s) in .claude/commands/ duplicate a plugin skill and can be removed:")
        for f in removable_commands:
            print(f"  {f.relative_to(project_path)}")
        if not dry_run:
            for f in removable_commands:
                f.unlink()
                print(f"  Removed: {f.relative_to(project_path)}")
        else:
            print("  (will be removed with --apply)")
    else:
        print("\nNo legacy command files found in .claude/commands/ to remove.")

    # --- 7. Replace utility hooks with plugin shims ---
    to_replace, already_shimmed = _find_shim_candidates(project_path)
    if to_replace:
        print(f"\n{len(to_replace)} utility hook(s) in .claude/hooks/ will be replaced by plugin shim:")
        for f in to_replace:
            print(f"  {f.relative_to(project_path)}")
        if not dry_run:
            for f in to_replace:
                f.write_text(_render_shim(f.stem))
                print(f"  Shimmed: {f.relative_to(project_path)}")
        else:
            print("  (will be replaced by plugin shim with --apply)")
    else:
        print("\nNo utility hooks to replace with plugin shim.")
    if already_shimmed:
        print(f"{len(already_shimmed)} utility hook(s) already shimmed (unchanged):")
        for f in already_shimmed:
            print(f"  {f.relative_to(project_path)}")

    print()
    if dry_run:
        print("Dry run complete. Use --apply to apply changes.")
    else:
        print("Migration complete.")


def main() -> None:
    if len(sys.argv) < 2 or sys.argv[1] in ("-h", "--help"):
        print(__doc__)
        sys.exit(0)

    project_path = Path(sys.argv[1]).resolve()

    if not project_path.exists():
        print(f"ERROR: Path does not exist: {project_path}")
        sys.exit(1)

    apply = "--apply" in sys.argv
    migrate(project_path, dry_run=not apply)


if __name__ == "__main__":
    main()
