#!/usr/bin/env python3
"""
Migrate existing OpenSpec project to Plugin Mode (v3.2)

Scans .claude/settings.json and removes hook commands that reference
local .claude/hooks/*.py files which are now provided by the plugin.
Also removes legacy .claude/commands/*.md files that duplicate a
plugin-provided skill of the same name (causes double slash-command
entries in the palette, see issue #24).

The plugin's hooks/hooks.json already declares all core hooks globally
for every project with the plugin enabled. Project-level settings.json
must NOT use ${CLAUDE_PLUGIN_ROOT} — that variable is only valid inside
a plugin's own hooks/hooks.json.

Handles both legacy command formats:
  v2 wrapper: if [ -f "${CLAUDE_PROJECT_DIR}/.claude/hooks/foo.py" ]; then python3 ... ; fi
  v3 direct:  python3 /absolute/path/.claude/hooks/foo.py

Usage:
    python3 migrate_to_plugin.py /path/to/project          # Dry run
    python3 migrate_to_plugin.py /path/to/project --apply  # Apply changes
"""

import json
import re
import sys
from pathlib import Path

PLUGIN_ROOT = Path(__file__).parent

# Eine Quelle fuer Format und Wortlaut — setup.py schreibt dieselbe Datei.
sys.path.insert(0, str(PLUGIN_ROOT))
from setup import (  # noqa: E402
    PLUGIN_MODE_VERSION_SOURCE,
    PLUGIN_MODE_VERSION_NOTE,
    PROJECT_DIR_PLACEHOLDER,
)

# Core hooks — live in ${CLAUDE_PLUGIN_ROOT}/core/hooks/
# These are deleted from a project's .claude/hooks/ on --apply (the plugin
# provides them globally). NOTE: hook_utils.py and config_loader.py are NOT
# here — they are shimmed instead (see SHIM_HOOKS), because project-own hooks
# import them and blind deletion would break every such hook.
CORE_HOOKS = {
    "edit_gate.py",
    "bash_gate.py",
    "post_bash.py",
    "phase_listener.py",
    "session_singleton_guard.py",
    "qa_gate.py",
    "override_token.py",
    "workflow.py",
    "migrate_state.py",
    "adversary_dialog.py",
    "claude_md_protection.py",
    "edit_verify.py",
    "post_implementation_gate.py",
    "secrets_guard.py",
    "tdd_enforcement.py",
    "worktree_write_guard.py",
}

# Module hooks — live in ${CLAUDE_PLUGIN_ROOT}/modules/<module>/hooks/
MODULE_HOOKS: dict[str, str] = {
    "ui_test_preflight.py": "ios-swiftui",
    "on_ui_test_failure.py": "ios-swiftui",
    "ui_test_debugger_hint.py": "ios-swiftui",
    "test_lock_guard.py": "ios-swiftui",
    "check_ha_restart.py": "home-assistant",
    "lovelace_screenshot_gate.py": "home-assistant",
}

# Shim hooks — utility modules that project-own hooks import directly
# (e.g. `from hook_utils import ...`). Instead of deleting these on --apply,
# we replace them with a thin shim that loads the real module from the
# installed plugin and re-exports its public attributes.
SHIM_HOOKS = {"hook_utils.py", "config_loader.py"}

# Marker on the first line of a generated shim (used for idempotency).
SHIM_MARKER = "# openspec-shim: resolves to installed plugin version"

# Shim body. __MODULE__ is replaced with the module name (e.g. hook_utils).
SHIM_TEMPLATE = '''# openspec-shim: resolves to installed plugin version
"""Shim for __MODULE__.py — generated by migrate_to_plugin.py (issue #33).

Project-own hooks import this module (e.g. ``import __MODULE__`` or
``from __MODULE__ import X``). Instead of keeping a stale local copy, this
shim loads the real module from the installed agent-os-openspec plugin and
re-exports all of its public attributes, so both import styles keep working.
"""
import importlib.util
import json
import os
import sys


def _resolve_plugin_module():
    registry = os.path.expanduser("~/.claude/plugins/installed_plugins.json")
    install_path = ""
    try:
        with open(registry) as _fh:
            _data = json.load(_fh)
        for _key, _entries in _data.get("plugins", {}).items():
            if not _key.startswith("agent-os-openspec@"):
                continue
            _entry = next(
                (_e for _e in _entries if _e.get("scope") == "user"),
                _entries[0],
            )
            install_path = _entry.get("installPath", "")
            break
    except Exception:
        install_path = ""

    if install_path:
        _hooks_dir = os.path.join(install_path, "core", "hooks")
        _module_path = os.path.join(_hooks_dir, "__MODULE__.py")
        if os.path.isfile(_module_path):
            # Das Plugin-Modul importiert Geschwister-Module (z.B.
            # `from hook_utils import ...` in config_loader.py). Ohne den
            # Hook-Ordner im Suchpfad scheitert der Import mit
            # ModuleNotFoundError, sobald der Shim geladen wird (#165).
            if _hooks_dir not in sys.path:
                sys.path.insert(0, _hooks_dir)
            _spec = importlib.util.spec_from_file_location(
                "__MODULE__", _module_path
            )
            _module = importlib.util.module_from_spec(_spec)
            _spec.loader.exec_module(_module)
            return _module

    raise ImportError(
        "agent-os-openspec plugin not installed "
        "— install it or restore local hooks"
    )


globals().update(
    {
        _name: _value
        for _name, _value in vars(_resolve_plugin_module()).items()
        if not _name.startswith("__")
    }
)
'''


def _render_shim(module_name: str) -> str:
    """Render the shim body for a given module name (e.g. 'hook_utils')."""
    return SHIM_TEMPLATE.replace("__MODULE__", module_name)


def _is_shim(path: Path) -> bool:
    """True if the file's first line is the shim marker."""
    try:
        with path.open() as fh:
            first_line = fh.readline().rstrip("\n")
    except Exception:
        return False
    return first_line == SHIM_MARKER


def _find_shim_candidates(project_path: Path) -> tuple[list[Path], list[Path]]:
    """
    Return (to_replace, already_shimmed) for SHIM_HOOKS present in the project.

    - to_replace: real local copies that should become a shim, PLUS veraltete
      Shims, deren Inhalt von der heutigen Fassung abweicht. Ein Shim mit
      bekanntem Fehler bliebe sonst ewig liegen: Der Marker ist derselbe, und
      reine Marker-Pruefung haelt ihn faelschlich fuer aktuell (#165 —
      Geschwister-Import).
    - already_shimmed: Shims, die bereits der heutigen Fassung entsprechen.
    """
    hooks_dir = project_path / ".claude" / "hooks"
    if not hooks_dir.exists():
        return [], []
    to_replace: list[Path] = []
    already_shimmed: list[Path] = []
    for name in sorted(SHIM_HOOKS):
        f = hooks_dir / name
        if not f.exists():
            continue
        if not _is_shim(f):
            to_replace.append(f)
            continue
        current = _render_shim(name.removesuffix(".py"))
        try:
            is_current = f.read_text() == current
        except Exception:
            is_current = False
        (already_shimmed if is_current else to_replace).append(f)
    return to_replace, already_shimmed

# .py filename regex — matches "foo_bar.py" or "foo-bar.py"
_PY_RE = re.compile(r'([\w][\w\-]*\.py)')


def _parse_hook_command(command: str) -> tuple[str | None, list[str]]:
    """
    Extract (py_filename, extra_args) from any hook command format.

    Works with both:
      python3 /abs/path/file.py arg1
      if [ -f "...file.py" ]; then python3 "...file.py" arg1; fi
    """
    py_files = _PY_RE.findall(command)
    if not py_files:
        return None, []

    filename = py_files[-1]

    # Text after the last .py occurrence → extra args
    last_pos = command.rfind(filename) + len(filename)
    tail = command[last_pos:]
    # Strip shell syntax: quotes, semicolons, "fi"
    tail = re.sub(r'["\';]|\bfi\b', ' ', tail).strip()
    args = tail.split() if tail else []

    return filename, args


_REMOVE = "__REMOVE__"


def _migrate_command(command: str) -> str | None:
    """
    Return _REMOVE if the command references a plugin-provided hook (should be deleted),
    or None if the command is unrelated to the plugin.

    ${CLAUDE_PLUGIN_ROOT} must NOT appear in project-level settings.json — the plugin's
    own hooks/hooks.json already registers all core hooks globally.
    """
    filename, _args = _parse_hook_command(command)
    if not filename:
        return None
    if filename in CORE_HOOKS or filename in MODULE_HOOKS:
        return _REMOVE
    return None


# Die Hook-Datei selbst — der einzige zuverlaessige Ankerpunkt im Kommando.
_HOOK_FILE_RE = re.compile(r"\.claude/hooks/(?P<name>[\w.\-]+\.py)")

# Ein Token, das damit beginnt, ist ein Pfad-Anfang und nichts anderes.
_PATH_SIGILS = ("/", "~/", "./", "../")

# Basisnamen, die als Interpreter gelten. Diese Liste wird AUSSCHLIESSLICH auf
# den Kopf des Aufrufs angewandt — das erste Token nach etwaigen
# Env-Zuweisungen. Sie auf jedes Token der Linkserweiterung anzuwenden war
# Adversary-Befund F006: Ein Ordner, der `env`, `node` oder `python3` heisst,
# beendete die Suche mitten im Pfad, und der Teil davor blieb als eigenes Token
# stehen. Der Interpreter steht am Anfang des Kommandos, nie mitten im Pfad.
_INTERPRETERS = {
    "python", "python2", "python3", "sh", "bash", "zsh", "env",
    "node", "ruby", "perl",
}

# Vorangestellte Env-Zuweisung (`WF=1 python3 …`) — gehoert zum Praefix, nicht
# zum Aufruf-Kopf.
_ENV_ASSIGNMENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*=")

# Token, ueber das die Linkssuche nie hinweglaeuft: Shell-Operator oder
# Schalter. Beides gehoert nie zu einem Dateipfad.
_STOP_TOKEN_RE = re.compile(r"[;&|()<>]|^-")


def _token_start(text: str, index: int) -> int:
    """Anfang des Tokens (Leerraum- und Quote-frei), das `index` enthaelt."""
    start = index
    while start > 0 and text[start - 1] not in " \t\"'":
        start -= 1
    return start


def _head_start(command: str) -> int:
    """Position des Aufruf-Kopfs — erstes Token, das keine Env-Zuweisung ist.

    Trennt an Leerraum, nicht nur an Leerzeichen: Eine eigene Tokenisierung
    lief hier bei einem Tabulator gegen die des uebrigen Codes, der Kopf wurde
    nie erkannt, und die Linkssuche loeschte Praefix und Interpreter gleich mit
    (Adversary-Befund F008).
    """
    for token in re.finditer(r"\S+", command):
        if not _ENV_ASSIGNMENT_RE.match(token.group(0)):
            return token.start()
    return 0


def _is_interpreter(token: str) -> bool:
    return token.strip("\"'").rsplit("/", 1)[-1] in _INTERPRETERS


def _path_span(command: str, match: re.Match) -> "tuple[int, int]":
    """Anfang und Ende des Pfads, zu dem die gefundene Hook-Datei gehoert.

    Von RECHTS aufgebaut: Die Hook-Datei ist der sichere Anker, der Anfang wird
    tokenweise nach links gesucht. Links zu beginnen ginge schief, sobald der
    Interpreter selbst absolut geschrieben ist (`/usr/bin/python3 …`) — dann
    waere er das erste Token mit Pfad-Sigel und wuerde mitverschluckt
    (Adversary-Befund F004).

    Erweitert wird, bis ein Token mit Pfad-Sigel den Anfang markiert. Der Kopf
    des Aufrufs (erstes Token nach Env-Zuweisungen) wird nur dann einbezogen,
    wenn er selbst ein Pfad ist UND kein Interpreter — `/usr/bin/python3` ist
    der Aufrufer, `/Users/hem/My` der Anfang eines Pfads.

    Das ENDE ist immer das Ende der Hook-Datei. Bis zum naechsten Leerzeichen
    weiterzulaufen wuerde ein angehaengtes Trennzeichen mitverschlucken: aus
    `… python3 /p/.claude/hooks/x.py; fi` wuerde `… python3 "…" fi`.
    """
    end = match.end()
    start = _token_start(command, match.start())

    token = command[start:end]
    # Normalfall `.claude/hooks/x.py` und jeder Pfad, der selbst mit einem
    # Sigel beginnt: das Token IST der Pfad, keine Erweiterung noetig.
    if token.startswith(_PATH_SIGILS) or token == match.group(0):
        return start, end

    # Sonst kann der Pfad ueber Leerzeichen reichen (`/Users/My Projekt/…`).
    # Nach links, Token fuer Token, bis ein Sigel-Token den Anfang markiert.
    head_start = _head_start(command)
    cursor = start
    while cursor > 0 and command[cursor - 1] in " \t":
        prev_end = cursor - 1
        while prev_end > 0 and command[prev_end - 1] in " \t":
            prev_end -= 1
        prev_start = _token_start(command, prev_end - 1)
        prev_token = command[prev_start:prev_end]
        if not prev_token:
            break
        if prev_start == head_start:
            # Der Kopf des Aufrufs. Ein Interpreter bleibt draussen, ein Pfad
            # gehoert dazu (Kommando ohne Interpreter, direkt ausgefuehrt).
            if prev_token.startswith(_PATH_SIGILS) and not _is_interpreter(prev_token):
                return prev_start, end
            break
        if prev_token.startswith(_PATH_SIGILS):
            return prev_start, end
        # Grenzen der Suche: Ein Shell-Operator, ein Schalter oder ein
        # Interpreter mitten im Kommando gehoert nie zu einem Pfad. Ohne diese
        # Grenze lief die Suche bis zum naechsten Sigel durch und verschluckte
        # fremde Kommandoteile (Adversary-Befund F009).
        if _STOP_TOKEN_RE.search(prev_token) or _is_interpreter(prev_token):
            break
        cursor = prev_start

    return cursor, end


def _anchor_command(command: str) -> str:
    """Verankert jeden .claude/hooks/-Pfad im Kommando an ${CLAUDE_PROJECT_DIR}.

    Hook-Kommandos laufen im aktuellen Arbeitsverzeichnis der Sitzung, nicht im
    Projekt-Root (https://code.claude.com/docs/en/hooks). Ein cwd-relativer Pfad
    (`python3 .claude/hooks/x.py`) bricht deshalb, sobald die Sitzung in einem
    Unterordner steht — gemeldet aus Meditationstimer, Issue #165. Ein
    eingebackener absoluter Pfad bricht beim Verschieben des Projekts.

    Interpreter, Env-Praefixe, Zusatzargumente und Shell-Huellen bleiben
    erhalten: ersetzt wird nur der Pfad. Umschliessende Anfuehrungszeichen
    werden mit ersetzt, damit keine verwaisten Quotes zurueckbleiben.
    Idempotent — ein bereits verankertes Kommando wird zeichengleich neu
    aufgebaut.

    Ein Kommando mit unpaarigen Anfuehrungszeichen wird unveraendert
    zurueckgegeben (Adversary-Befund F007). Was nicht verlaesslich gelesen
    werden kann, wird nicht umgeschrieben — ein halb ersetztes Kommando waere
    schlimmer als das unreparierte.
    """
    if command.count('"') % 2 or command.count("'") % 2:
        return command

    result = []
    cursor = 0
    for match in _HOOK_FILE_RE.finditer(command):
        if match.start() < cursor:
            continue  # bereits von einer vorherigen Ersetzung abgedeckt
        start, end = _path_span(command, match)
        # Umschliessende Anfuehrungszeichen mitnehmen
        if start > 0 and command[start - 1] in "\"'" and end < len(command) \
                and command[end] == command[start - 1]:
            start -= 1
            end += 1
        result.append(command[cursor:start])
        result.append(
            f'"{PROJECT_DIR_PLACEHOLDER}/.claude/hooks/{match.group("name")}"'
        )
        cursor = end
    result.append(command[cursor:])
    return "".join(result)


def _patch_settings(settings: dict, dry_run: bool) -> list[tuple[str, str, str]]:
    """
    Remove plugin hook commands from settings dict in-place, and anchor the
    remaining (project-own) hook commands at ${CLAUDE_PROJECT_DIR}.
    Returns list of (event_name, old_command, "<removed>" | new_command).
    """
    changes = []
    for event_name, event_entries in settings.get("hooks", {}).items():
        emptied = []
        for entry in event_entries:
            hooks_list = entry.get("hooks", [])
            to_remove = []
            for hook in hooks_list:
                old_cmd = hook.get("command", "")
                if _migrate_command(old_cmd) == _REMOVE:
                    changes.append((event_name, old_cmd, "<removed>"))
                    to_remove.append(hook)
                    continue
                new_cmd = _anchor_command(old_cmd)
                if new_cmd != old_cmd:
                    changes.append((event_name, old_cmd, new_cmd))
                    if not dry_run:
                        hook["command"] = new_cmd
            if to_remove:
                # Nur Eintraege, aus denen DIESER Lauf den letzten Hook nimmt.
                # Schon vorher leere Eintraege bleiben, wo sie sind: Das
                # Werkzeug raeumt nur auf, was es selbst geleert hat, und es
                # meldet das auch im Trockenlauf (Adversary-Befund F005).
                if len(to_remove) == len(hooks_list):
                    matcher = entry.get("matcher", "")
                    label = f'<leerer Eintrag: {matcher}>' if matcher \
                        else "<leerer Eintrag>"
                    changes.append((event_name, label, "<removed>"))
                    emptied.append(entry)
                if not dry_run:
                    for h in to_remove:
                        hooks_list.remove(h)
        if not dry_run and emptied:
            event_entries[:] = [
                e for e in event_entries
                if not any(e is dead for dead in emptied)
            ]
    return changes


def _find_removable_hook_files(project_path: Path) -> list[Path]:
    """Return .claude/hooks/*.py files that are provided by the plugin."""
    hooks_dir = project_path / ".claude" / "hooks"
    if not hooks_dir.exists():
        return []
    removable = CORE_HOOKS | set(MODULE_HOOKS.keys())
    return [f for f in hooks_dir.glob("*.py") if f.name in removable]


def _normalize_command_text(text: str) -> str:
    """Vergleichsform: ohne Alias-Kommentar, ohne Versions-Marker, ohne Leerraum-Rauschen.

    Der Marker `⚙ /<befehl> · agent-os-openspec <version>` (seit 3.24.0) steht am
    Ende jeder generierten Fassung. Er unterscheidet zwei ansonsten identische
    Dateien nur durch die Versionsnummer und darf eine echte Kopie nicht vor dem
    Aufraeumen schuetzen.
    """
    lines = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("<!-- openspec-alias:"):
            continue
        if stripped.startswith("⚙ /"):
            continue
        lines.append(line.rstrip())
    return "\n".join(lines).strip()


def _classify_command_files(project_path: Path) -> "tuple[list[Path], list[Path]]":
    """(nachweisliche Kopien, abweichende Dateien) unter .claude/commands/.

    Legacy-Installationen kopierten `core/commands/*.md` direkt ins Projekt. Mit
    aktivem Plugin erscheint derselbe Befehl ein ZWEITES Mal in der Palette —
    diese Doppelungen soll das Werkzeug entfernen.

    Frueher galt dafuer allein die Namensgleichheit mit einem Plugin-Skill. Das
    ist kein Duplikat-Beweis: `70-deploy` ist laut CLAUDE.md ausdruecklich ein
    projektspezifisches Template, das angepasst werden MUSS. In gregor_zwanzig
    stand dort die vollstaendige Produktions-Deploy-Prozedur — sie wurde zum
    Loeschen vorgeschlagen (Issue #160).

    Entfernt wird deshalb nur noch, was nachweislich eine Kopie ist:
    inhaltsgleich zum ausgelieferten Skill nach `_normalize_command_text`.
    Alles andere landet in der zweiten Liste, bleibt stehen und wird berichtet.

    Bewusst KEIN Aehnlichkeitsmass: an echten Daten gemessen streuen Alt-Kopien
    zwischen 0.22 und 0.64 Aehnlichkeit, eine echte Anpassung lag bei 0.03. Eine
    Schwelle dazwischen waere geraten, und die Fehlerkosten sind asymmetrisch —
    eine uebersehene Doppelung kostet einen Eintrag in der Befehlsliste, eine
    faelschlich geloeschte Datei eine Produktionsprozedur.

    Alias-Marker, fehlender Skill und unlesbarer Inhalt schuetzen wie bisher.
    """
    commands_dir = project_path / ".claude" / "commands"
    if not commands_dir.exists():
        return [], []
    skills_dir = PLUGIN_ROOT / "skills"
    if not skills_dir.exists():
        return [], []
    provided = {p.name for p in skills_dir.iterdir() if p.is_dir()}
    duplicates: list[Path] = []
    divergent: list[Path] = []
    for f in sorted(commands_dir.glob("*.md")):
        if f.stem not in provided:
            continue
        try:
            content = f.read_text()
        except Exception:
            # Unreadable (binary/broken encoding): do not treat as removable.
            continue
        if "openspec-alias:" in content:
            continue
        skill = skills_dir / f.stem / "SKILL.md"
        try:
            shipped = skill.read_text()
        except Exception:
            divergent.append(f)
            continue
        if _normalize_command_text(content) == _normalize_command_text(shipped):
            duplicates.append(f)
        else:
            divergent.append(f)
    return duplicates, divergent


def _find_removable_command_files(project_path: Path) -> list[Path]:
    """Nur die nachweislichen Kopien. Beibehalten fuer bestehende Aufrufer."""
    return _classify_command_files(project_path)[0]


def _read_installed_modules(project_path: Path) -> list[str]:
    version_file = project_path / ".claude" / "framework_version.json"
    if version_file.exists():
        try:
            data = json.loads(version_file.read_text())
            return data.get("installed_modules", [])
        except Exception:
            pass
    return []


def _print_changes(changes: list[tuple[str, str, str]]) -> None:
    """Gibt die Kommando-Aenderungen einheitlich aus (entfernt / verankert)."""
    for event_name, old_cmd, action in changes:
        short_old = old_cmd if len(old_cmd) <= 80 else old_cmd[:77] + "..."
        print(f"  [{event_name}] {short_old}")
        if action == "<removed>":
            print("           → <removed> (already provided by plugin hooks/hooks.json)")
        else:
            short_new = action if len(action) <= 80 else action[:77] + "..."
            print(f"           → {short_new}")
            print("             (an ${CLAUDE_PROJECT_DIR} verankert — Issue #165)")


def _patch_local_settings(project_path: Path, dry_run: bool) -> None:
    """settings.local.json mitnehmen, falls sie Hooks registriert (Issue #165).

    Fehlende Datei, fehlender hooks-Abschnitt oder unlesbares JSON sind kein
    Fehler: settings.json ist bereits migriert, dieser Schritt ergaenzt nur.
    """
    local_path = project_path / ".claude" / "settings.local.json"
    if not local_path.exists():
        return
    try:
        local_settings = json.loads(local_path.read_text())
    except Exception as exc:
        print(f"\nWARNUNG: .claude/settings.local.json ist nicht lesbar ({exc}) — uebersprungen.")
        return
    if not local_settings.get("hooks"):
        return

    print("\nScanning hook commands in .claude/settings.local.json ...")
    local_changes = _patch_settings(local_settings, dry_run)
    if not local_changes:
        print("  Nichts zu aendern.")
        return
    print(f"Found {len(local_changes)} hook command(s) to change in settings.local.json:")
    _print_changes(local_changes)
    if not dry_run:
        local_path.write_text(json.dumps(local_settings, indent=2))
        print("\nWritten: .claude/settings.local.json")


def migrate(project_path: Path, dry_run: bool = True) -> None:
    print(f"OpenSpec Plugin Migration")
    print(f"=========================")
    print(f"Project : {project_path}")
    print(f"Mode    : {'Dry Run (pass --apply to apply)' if dry_run else 'APPLY'}")
    print()

    if not (project_path / ".claude").exists():
        print("ERROR: .claude/ directory not found. Is this an OpenSpec project?")
        sys.exit(1)

    settings_path = project_path / ".claude" / "settings.json"
    if not settings_path.exists():
        print("ERROR: .claude/settings.json not found.")
        sys.exit(1)

    settings = json.loads(settings_path.read_text())
    wrote_settings = False

    # --- 1. Patch hook commands ---
    print("Scanning hook commands in .claude/settings.json ...")
    changes = _patch_settings(settings, dry_run)
    if changes:
        print(f"Found {len(changes)} hook command(s) to change in settings.json:")
        _print_changes(changes)
        wrote_settings = True
    else:
        print("  No plugin hook commands found in settings.json.")

    # --- 1b. Same treatment for settings.local.json (Issue #165) ---
    # Auch dort koennen Hooks registriert sein; der permissions-Abschnitt
    # bleibt unberuehrt, weil _patch_settings nur unter "hooks" arbeitet.
    _patch_local_settings(project_path, dry_run)

    # --- 2. Add OPENSPEC_ENABLED_MODULES ---
    modules = _read_installed_modules(project_path)
    env_section = settings.get("env", {})
    if modules and "OPENSPEC_ENABLED_MODULES" not in env_section:
        value = ",".join(modules)
        print(f"\nWill add env.OPENSPEC_ENABLED_MODULES = '{value}'")
        if not dry_run:
            settings.setdefault("env", {})[" OPENSPEC_ENABLED_MODULES"] = value
            settings["env"] = {k.strip(): v for k, v in settings["env"].items()}
        wrote_settings = True
    elif "OPENSPEC_ENABLED_MODULES" in env_section:
        print(f"\nenv.OPENSPEC_ENABLED_MODULES already set: {env_section['OPENSPEC_ENABLED_MODULES']}")

    # --- 3. Write settings.json ---
    if not dry_run and wrote_settings:
        settings_path.write_text(json.dumps(settings, indent=2))
        print(f"\nWritten: .claude/settings.json")

    # --- 4. Mark framework_version.json as plugin_mode ---
    # Die alte Copy-Mode-Zahl muss dabei WEG. Ab hier laufen Aktualisierungen
    # ueber `claude plugin update`, das diese Datei nie anfasst — die Zahl waere
    # ab sofort eine Falschauskunft (gemessen: gregor_zwanzig stand auf 3.4.13,
    # ausgeliefert war 3.25.1). Geprueft wird deshalb nicht nur `plugin_mode`,
    # sondern auch die Zahl selbst: ein bereits gesetztes `plugin_mode` darf die
    # Falschauskunft nicht konservieren, sonst braucht jedes Bestandsprojekt
    # Handarbeit.
    version_file = project_path / ".claude" / "framework_version.json"
    if version_file.exists():
        try:
            version_data = json.loads(version_file.read_text())
            stale_version = version_data.get("framework_version")
            needs_update = (
                not version_data.get("plugin_mode")
                or stale_version is not None
                or version_data.get("version_source") != PLUGIN_MODE_VERSION_SOURCE
            )
            if needs_update:
                print("\nWill mark framework_version.json as plugin_mode=true")
                if stale_version is not None:
                    print(f"  Copy-Mode-Version {stale_version!r} wird entfernt — im "
                          "Plugin-Modus kennt diese Datei die geladene Version nicht.")
                if not dry_run:
                    version_data["plugin_mode"] = True
                    version_data["framework_version"] = None
                    version_data["version_source"] = PLUGIN_MODE_VERSION_SOURCE
                    version_data["note"] = PLUGIN_MODE_VERSION_NOTE
                    version_file.write_text(json.dumps(version_data, indent=2))
                    print("  Written: .claude/framework_version.json")
        except Exception:
            pass

    # --- 5. Remove plugin hook files ---
    removable = _find_removable_hook_files(project_path)
    if removable:
        print(f"\n{len(removable)} plugin hook file(s) in .claude/hooks/ can be removed:")
        for f in removable:
            print(f"  {f.relative_to(project_path)}")
        if not dry_run:
            for f in removable:
                f.unlink()
                print(f"  Removed: {f.relative_to(project_path)}")
        else:
            print("  (will be removed with --apply)")
    else:
        print("\nNo plugin hook files found in .claude/hooks/ to remove.")

    # --- 6. Remove legacy command files that duplicate plugin skills ---
    removable_commands, divergent_commands = _classify_command_files(project_path)
    if divergent_commands:
        print(f"\n{len(divergent_commands)} Befehlsdatei(en) in .claude/commands/ tragen den Namen "
              "eines Plugin-Skills, weichen aber inhaltlich ab — EIGENE FASSUNG, bleibt stehen:")
        for f in divergent_commands:
            print(f"  {f.relative_to(project_path)}")
        print("  (wird NICHT entfernt. Namensgleichheit ist kein Duplikat-Beweis — `70-deploy`")
        print("   etwa ist ausdruecklich projektspezifisch. Pruefen und ggf. selbst loeschen.)")
    if removable_commands:
        print(f"\n{len(removable_commands)} legacy command file(s) in .claude/commands/ duplicate a plugin skill and can be removed:")
        for f in removable_commands:
            print(f"  {f.relative_to(project_path)}")
        if not dry_run:
            for f in removable_commands:
                f.unlink()
                print(f"  Removed: {f.relative_to(project_path)}")
        else:
            print("  (will be removed with --apply)")
    else:
        print("\nNo legacy command files found in .claude/commands/ to remove.")

    # --- 7. Replace utility hooks with plugin shims ---
    to_replace, already_shimmed = _find_shim_candidates(project_path)
    if to_replace:
        print(f"\n{len(to_replace)} utility hook(s) in .claude/hooks/ will be replaced by plugin shim:")
        for f in to_replace:
            print(f"  {f.relative_to(project_path)}")
        if not dry_run:
            for f in to_replace:
                f.write_text(_render_shim(f.stem))
                print(f"  Shimmed: {f.relative_to(project_path)}")
        else:
            print("  (will be replaced by plugin shim with --apply)")
    else:
        print("\nNo utility hooks to replace with plugin shim.")
    if already_shimmed:
        print(f"{len(already_shimmed)} utility hook(s) already shimmed (unchanged):")
        for f in already_shimmed:
            print(f"  {f.relative_to(project_path)}")

    print()
    if dry_run:
        print("Dry run complete. Use --apply to apply changes.")
    else:
        print("Migration complete.")


def main() -> None:
    if len(sys.argv) < 2 or sys.argv[1] in ("-h", "--help"):
        print(__doc__)
        sys.exit(0)

    project_path = Path(sys.argv[1]).resolve()

    if not project_path.exists():
        print(f"ERROR: Path does not exist: {project_path}")
        sys.exit(1)

    apply = "--apply" in sys.argv
    migrate(project_path, dry_run=not apply)


if __name__ == "__main__":
    main()
